[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
# runner = "picotool load -u -v -x -t elf"

[alias]
run-pico = "run -p rocket_vR --target thumbv6m-none-eabi --features rp2040"
run-pico2 = "run -p rocket_vR --target thumbv8m.main-none-eabihf --features rp2350"
build-pico = "build -p rocket_vR --target thumbv6m-none-eabi --features rp2040"
build-pico2 = "build -p rocket_vR --target thumbv8m.main-none-eabihf --features rp2350"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
